# Generated by Django 4.0.5 on 2022-07-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_equipo_estadisticas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticas',
            name='goles',
            field=models.IntegerField(),
        ),
    ]
